apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: us.gcr.io/ticketing-dev-345514/auth
          env:
            - name: JWT_KEY #create an env variable inside the container with the name JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret #name of the secret key
                  key: JWT_KEY #key of the secret key
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
